#!/usr/bin/env bash
# hivemind installer / upgrader — Linux only.
#
# DEFAULT (no flags): downloads prebuilt binaries from the latest GitHub
# Release. Needs only `curl`, `bash`, glibc, and the `claude` CLI on PATH.
# No node / pnpm / bun required.
#
#   curl -fsSL https://raw.githubusercontent.com/dip497/hivemind/main/install.sh | bash
#
# WITH `--dev`: clones the source repo and builds locally. Needs `git`,
# `node` ≥ 22, `pnpm` ≥ 10, `bun` ≥ 1.1. Use this if you want to hack on
# hivemind or if no prebuilt is published for your platform yet.
#
#   bash install.sh --dev
#
# Re-running the script in either mode UPGRADES the existing install:
#   - prebuilt mode → fetches the latest release if newer than installed
#   - dev mode      → `git pull --ff-only` + rebuild
#
# Installed users manage the app via the `hivemind` launcher:
#   hivemind upgrade            # re-run this installer (latest release)
#   hivemind uninstall          # remove app + launcher + desktop entry
#   hivemind uninstall --purge  # also delete ~/.config/hivemind (settings/sessions)
#
# Env knobs (rarely needed):
#   HIVEMIND_BIN_DIR  symlink dir (default: ~/.local/bin)
#   HIVEMIND_APP_DIR  where the AppImage / version metadata live
#                     (default: ~/.hivemind-app)
#   HIVEMIND_REPO     "owner/repo" for release downloads (default: dip497/hivemind)
#   HIVEMIND_VERSION  pin a specific release tag (default: latest)
#
set -euo pipefail

# ── colors ────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
say()  { printf '%b\n' "${BLUE}▸${NC} $*"; }
ok()   { printf '%b\n' "${GREEN}✓${NC} $*"; }
warn() { printf '%b\n' "${YELLOW}!${NC} $*"; }
die()  { printf '%b\n' "${RED}✗${NC} $*" >&2; exit 1; }

# Install the `hivemind` launcher as a WRAPPER (not a bare symlink) that runs
# the extracted app with `--no-sandbox`.
#
# Why: we EXTRACT the AppImage so it runs without libfuse2 (Ubuntu 22.04+ ships
# without it). But extraction strips the SUID-root bit from `chrome-sandbox`,
# and Electron's setuid sandbox then aborts ("SUID sandbox helper … not
# configured correctly"). On Ubuntu 24.04 the unprivileged-userns fallback is
# ALSO blocked by AppArmor — so the only no-root, cross-distro option is to
# disable the Chromium sandbox. hivemind renders only LOCAL trusted content
# (terminals, diffs, editor) and already has full local access by design, so
# this is an acceptable tradeoff (Obsidian / Cursor / LM-Studio AppImages take
# the same one). Users who want the sandbox can instead:
#   sudo chown root:root <app>/chrome-sandbox && sudo chmod 4755 <…>
write_launcher() {
  local apprun="$1"
  local appdir
  appdir="$(dirname "$apprun")"
  # CRITICAL: remove any existing launcher FIRST. Old installs left
  # `$BIN_DIR/hivemind` as a SYMLINK → the extracted AppRun. `cat >` follows a
  # symlink and writes to its TARGET, so without this rm the wrapper was
  # written straight INTO hivemind-extracted/AppRun, clobbering the genuine
  # AppRun with a script that execs itself (infinite loop / broken launch).
  rm -f "$BIN_DIR/hivemind"
  cat > "$BIN_DIR/hivemind" <<EOF
#!/usr/bin/env bash
# hivemind desktop launcher (generated by install.sh). --no-sandbox is required
# for the extracted AppImage — see install.sh write_launcher() for the why.
#
# \`hivemind upgrade\` re-runs the official installer (fetches the latest release,
# no-op if already current; pass --dev for a source install).
# \`hivemind uninstall\` removes the app, launcher and desktop entry (keeps your
# settings/sessions; pass --purge to delete ~/.config/hivemind too). Anything
# else launches the app.
if [ "\${1:-}" = "upgrade" ]; then
  shift
  exec bash -c 'curl -fsSL https://raw.githubusercontent.com/dip497/hivemind/main/install.sh | bash -s -- "\$@"' _ "\$@"
fi
if [ "\${1:-}" = "uninstall" ]; then
  shift
  purge=0; for a in "\$@"; do [ "\$a" = "--purge" ] && purge=1; done
  echo "hivemind: uninstalling…" >&2
  # Stop the running app + its background pty daemon. Match on the app dir so we
  # never kill THIS launcher process (it lives at a different path, in BIN_DIR).
  pkill -f "$appdir" 2>/dev/null || true
  data_dir="\${XDG_DATA_HOME:-\$HOME/.local/share}"
  rm -rf "$appdir" "${appdir}.staged"
  rm -f "\$data_dir/applications/hivemind.desktop" "\$data_dir/icons/hicolor/512x512/apps/hivemind.png"
  update-desktop-database "\$data_dir/applications" 2>/dev/null || true
  if [ "\$purge" = 1 ]; then
    rm -rf "\${XDG_CONFIG_HOME:-\$HOME/.config}/hivemind"
    echo "hivemind: removed user data (\${XDG_CONFIG_HOME:-\$HOME/.config}/hivemind)" >&2
  else
    echo "hivemind: kept user data — pass 'hivemind uninstall --purge' to remove it too" >&2
  fi
  rm -f "$BIN_DIR/hivemind"   # the launcher itself, LAST (safe: already in memory)
  echo "hivemind: uninstalled." >&2
  exit 0
fi
# Apply a staged upgrade: when the installer ran while the app was live it could
# not replace these files in place, so it extracted the new version beside this
# one. Swap it in now, before launch (this process is the fresh start).
if [ -d "${appdir}.staged" ]; then
  rm -rf "$appdir" && mv "${appdir}.staged" "$appdir" && echo "hivemind: applied staged upgrade" >&2
fi
#
# APPDIR must be exported explicitly: the bundled AppRun auto-detects APPDIR by
# walking up from itself looking for "\$1" as a file — but \$1 is "--no-sandbox"
# here, which is never a file, so the search collapses APPDIR to "" and it
# tries to exec "/hivemind" (ENOENT). Setting APPDIR makes AppRun skip the
# broken auto-detect.
export APPDIR="$appdir"
exec "$apprun" --no-sandbox "\$@"
EOF
  chmod +x "$BIN_DIR/hivemind"
}

# Install the GNOME/XDG desktop entry + hicolor icon so the app shows up in the
# app grid AND the running window maps to the real icon in the dock. The icon is
# already bundled inside the extracted AppImage (electron-builder ships it) — the
# installer just never copied it out, so the dock fell back to a generic icon and
# there was no launcher entry. StartupWMClass MUST equal app.setName("hivemind")
# (the window's WM_CLASS) or GNOME can't associate the window with this entry.
# Runs on every install/upgrade (idempotent).
install_desktop_entry() {
  local appdir="$1"  # the hivemind-extracted dir
  local data_dir="${XDG_DATA_HOME:-$HOME/.local/share}"
  local icon_dst="$data_dir/icons/hicolor/512x512/apps/hivemind.png"
  local desk_dst="$data_dir/applications/hivemind.desktop"
  # Prefer the proper hicolor source; fall back to the AppImage root icon.
  local icon_src="$appdir/usr/share/icons/hicolor/512x512/apps/hivemind.png"
  [ -f "$icon_src" ] || icon_src="$appdir/hivemind.png"
  if [ -f "$icon_src" ]; then
    mkdir -p "$(dirname "$icon_dst")" && cp -f "$icon_src" "$icon_dst"
  fi
  mkdir -p "$(dirname "$desk_dst")"
  cat > "$desk_dst" <<EOF
[Desktop Entry]
Type=Application
Name=hivemind
Comment=Infinite canvas for Claude Code & AI coding agents
Exec=$BIN_DIR/hivemind %U
Icon=hivemind
Terminal=false
Categories=Development;IDE;
StartupWMClass=hivemind
EOF
  chmod +x "$desk_dst" 2>/dev/null || true
  # Refresh the caches so the icon/entry appear without a re-login (best-effort).
  command -v update-desktop-database >/dev/null 2>&1 && update-desktop-database "$data_dir/applications" >/dev/null 2>&1 || true
  command -v gtk-update-icon-cache >/dev/null 2>&1 && gtk-update-icon-cache -f -t "$data_dir/icons/hicolor" >/dev/null 2>&1 || true
  ok "installed desktop entry + icon ($desk_dst)"
}

# Is a packaged hivemind instance live right now? Matches the bundled Electron /
# AppRun running out of our extracted dir. Used to avoid replacing files under a
# running app (e.g. `hivemind upgrade` run from a terminal tile inside the app).
hivemind_running() {
  if command -v pgrep >/dev/null 2>&1; then
    pgrep -f "$APP_DIR/hivemind-extracted/" >/dev/null 2>&1
  else
    ps -e -o args= 2>/dev/null | grep -Fq "$APP_DIR/hivemind-extracted/"
  fi
}

# Extract the downloaded AppImage into place. If the app is RUNNING, stage it
# beside the live dir instead of deleting the live one out from under the process
# — the launcher swaps the staged dir in on next start. Returns 0 = extracted in
# place, 1 = staged for next launch.
extract_appimage() {
  local live="$APP_DIR/hivemind-extracted"
  rm -rf "$APP_DIR/squashfs-root"
  (cd "$APP_DIR" && ./hivemind.AppImage --appimage-extract >/dev/null) \
    || die "AppImage extract failed. Check $APP_DIR/hivemind.AppImage"
  if hivemind_running; then
    rm -rf "${live}.staged"
    mv "$APP_DIR/squashfs-root" "${live}.staged"
    return 1
  fi
  rm -rf "$live"
  mv "$APP_DIR/squashfs-root" "$live"
  return 0
}

# ── platform gate ─────────────────────────────────────────────────────────
[ "$(uname -s)" = "Linux" ] || die "Linux only for now (got $(uname -s))."
[ "$(uname -m)" = "x86_64" ] || die "x86_64 only for now (got $(uname -m)). Use --dev to build locally."

# ── flags ─────────────────────────────────────────────────────────────────
MODE="prebuilt"
for arg in "$@"; do
  case "$arg" in
    --dev|--source|--from-source) MODE="dev" ;;
    -h|--help)
      sed -n '2,18p' "$0"
      exit 0
      ;;
    *) warn "unknown flag: $arg" ;;
  esac
done

BIN_DIR="${HIVEMIND_BIN_DIR:-$HOME/.local/bin}"
APP_DIR="${HIVEMIND_APP_DIR:-$HOME/.hivemind-app}"
REPO="${HIVEMIND_REPO:-dip497/hivemind}"
mkdir -p "$BIN_DIR" "$APP_DIR"

# ── PREBUILT path ─────────────────────────────────────────────────────────
install_prebuilt() {
  command -v curl >/dev/null 2>&1 || die "curl missing — install: sudo apt install curl"

  # Resolve target version (latest by default).
  if [ -n "${HIVEMIND_VERSION:-}" ]; then
    TAG="$HIVEMIND_VERSION"
  else
    say "resolving latest release of $REPO"
    TAG=$(curl -fsSL "https://api.github.com/repos/$REPO/releases/latest" \
      | grep -oE '"tag_name":\s*"[^"]+"' \
      | sed -E 's/.*"([^"]+)".*/\1/' | head -1) \
      || die "could not reach github.com api — check your network"
    [ -n "$TAG" ] || die "no published releases yet for $REPO. Try --dev to build from source."
  fi
  say "target version: $TAG"

  # Skip download if already on this version — but SELF-HEAL the launcher
  # first. Earlier installs symlinked `hivemind` straight to AppRun, which
  # aborts on the SUID-sandbox error; re-running the installer should repair
  # that to the --no-sandbox wrapper even when the version hasn't changed.
  INSTALLED_FILE="$APP_DIR/.installed-version"
  if [ -f "$INSTALLED_FILE" ] && [ "$(cat "$INSTALLED_FILE")" = "$TAG" ]; then
    APPRUN="$APP_DIR/hivemind-extracted/AppRun"
    # Heal a CORRUPTED AppRun: the old buggy launcher wrote its wrapper THROUGH
    # the `hivemind` symlink into AppRun itself (a 3-line self-exec script). A
    # genuine electron-builder AppRun is hundreds of lines and defines BIN=. If
    # AppRun looks like the wrapper (or is tiny), re-extract from the AppImage.
    if [ -f "$APPRUN" ] && ! grep -q 'BIN=' "$APPRUN" 2>/dev/null && [ -f "$APP_DIR/hivemind.AppImage" ]; then
      warn "detected corrupted AppRun — re-extracting AppImage"
      if extract_appimage; then ok "re-extracted AppImage"; else warn "app is running — re-extract staged; restart hivemind to apply"; fi
    fi
    # Always (re)write the launcher to the current format — idempotent, and
    # upgrades old symlink/no-APPDIR launchers to the working wrapper.
    if [ -x "$APPRUN" ]; then
      write_launcher "$APPRUN"
      install_desktop_entry "$APP_DIR/hivemind-extracted"
      ok "launcher up to date (--no-sandbox wrapper)"
    fi
    ok "already on $TAG — nothing to do"
    return 0
  fi

  CLI_URL="https://github.com/$REPO/releases/download/$TAG/hive-linux-x86_64"
  # AppImage filename includes the bare version (no leading 'v').
  VERSION_BARE="${TAG#v}"
  APPIMG_URL="https://github.com/$REPO/releases/download/$TAG/hivemind-${VERSION_BARE}-x86_64.AppImage"

  say "downloading hive CLI"
  # Download to a temp file then atomically mv into place. A direct `curl -o`
  # over the live binary fails with "text file busy" when the CLI is in use
  # (a running app's claude tiles invoke the hive MCP binary) — rename swaps the
  # name while the old inode keeps serving the running process.
  curl -fL --progress-bar -o "$APP_DIR/hive.new" "$CLI_URL" \
    || die "CLI download failed from $CLI_URL"
  chmod +x "$APP_DIR/hive.new"
  mv -f "$APP_DIR/hive.new" "$APP_DIR/hive"
  ln -sf "$APP_DIR/hive" "$BIN_DIR/hive"
  ok "linked $BIN_DIR/hive → $APP_DIR/hive"

  say "downloading desktop AppImage"
  # Same temp-then-mv: avoids a half-written AppImage on interrupt and a
  # busy-file clobber if the file is ever held open.
  if curl -fL --progress-bar -o "$APP_DIR/hivemind.AppImage.new" "$APPIMG_URL"; then
    mv -f "$APP_DIR/hivemind.AppImage.new" "$APP_DIR/hivemind.AppImage"
    chmod +x "$APP_DIR/hivemind.AppImage"
    # Extract instead of FUSE-mount at runtime. Ubuntu 22.04+ ships without
    # libfuse2; running the AppImage directly errors with "dlopen():
    # libfuse.so.2". Extract sidesteps the dependency — `AppRun` is a normal
    # ELF that re-execs the bundled Electron. ~5s one-time cost, zero sudo.
    say "extracting AppImage (no libfuse2 needed)"
    if extract_appimage; then
      write_launcher "$APP_DIR/hivemind-extracted/AppRun"
      install_desktop_entry "$APP_DIR/hivemind-extracted"
      ok "installed launcher $BIN_DIR/hivemind → $APP_DIR/hivemind-extracted/AppRun"
    else
      # App is live — upgrade staged beside the running one; the launcher swaps
      # it in on next start. Rewrite the launcher (so the swap block is present)
      # and install the NEW icon from the staged tree (safe; touches only
      # ~/.local/share, not the running process).
      write_launcher "$APP_DIR/hivemind-extracted/AppRun"
      install_desktop_entry "$APP_DIR/hivemind-extracted.staged"
      warn "hivemind is running — upgrade STAGED. Quit & reopen hivemind to apply it. Your canvas + sessions are safe; nothing is lost."
    fi
  else
    warn "AppImage download failed (CLI still installed). Run \`hivemind\` via --dev or re-run later."
  fi

  echo "$TAG" > "$INSTALLED_FILE"
  ok "installed $TAG"
}

# ── DEV path (source build) ───────────────────────────────────────────────
install_dev() {
  REPO_URL="${HIVEMIND_REPO_URL:-https://github.com/$REPO.git}"
  HIVE_ROOT="$APP_DIR"

  if [ -f "package.json" ] && grep -q '"name": "hivemind"' package.json 2>/dev/null; then
    HIVE_ROOT="$(pwd)"
    say "running inside existing hivemind checkout: $HIVE_ROOT"
    if [ -d "$HIVE_ROOT/.git" ] && command -v git >/dev/null 2>&1; then
      say "git pull --ff-only"
      git -C "$HIVE_ROOT" pull --ff-only || warn "pull failed — building current sources"
    fi
  elif [ -d "$HIVE_ROOT/.git" ]; then
    say "upgrading existing checkout at $HIVE_ROOT"
    git -C "$HIVE_ROOT" pull --ff-only
  else
    say "fresh dev install — cloning $REPO_URL → $HIVE_ROOT"
    command -v git >/dev/null 2>&1 || die "git missing — install: sudo apt install git"
    git clone --depth 1 "$REPO_URL" "$HIVE_ROOT"
  fi

  cd "$HIVE_ROOT"

  # Dep checks (only enforced in --dev).
  need() {
    local cmd=$1; local install_hint=$2
    if command -v "$cmd" >/dev/null 2>&1; then
      ok "$cmd → $(command -v "$cmd")"
    else
      die "$cmd missing. Install: $install_hint"
    fi
  }
  say "checking dev deps"
  need git    "sudo apt install git"
  need node   "use nvm: https://github.com/nvm-sh/nvm — then 'nvm install 22'"
  need pnpm   "npm i -g pnpm"
  need bun    "curl -fsSL https://bun.sh/install | bash"
  NODE_MAJOR=$(node -v | sed 's/^v\([0-9]*\).*/\1/')
  [ "$NODE_MAJOR" -ge 22 ] || die "node ≥ 22 required (have $(node -v))"

  say "pnpm install"
  pnpm install --silent

  say "building CLI"
  pnpm --filter @hivemind/cli run build
  HIVE_BIN="$HIVE_ROOT/apps/cli/dist/hive"
  [ -x "$HIVE_BIN" ] || die "CLI build produced no binary at $HIVE_BIN"
  ln -sf "$HIVE_BIN" "$BIN_DIR/hive"
  ok "linked $BIN_DIR/hive → $HIVE_BIN"

  say "building renderer + main"
  pnpm --filter @hivemind/desktop run build

  if [ "${HIVEMIND_SKIP_APPIMAGE:-0}" = "0" ]; then
    say "packaging AppImage"
    if pnpm --filter @hivemind/desktop run dist 2>&1 | tail -5; then
      APPIMAGE=$(ls -1 "$HIVE_ROOT"/apps/desktop/dist-electron/*.AppImage 2>/dev/null | head -1)
      if [ -n "$APPIMAGE" ]; then
        chmod +x "$APPIMAGE"
        # Extract — Ubuntu 22.04+ lacks libfuse2 by default.
        EXTRACT_DIR="$APP_DIR/hivemind-extracted"
        rm -rf "$EXTRACT_DIR"
        (cd "$APP_DIR" && "$APPIMAGE" --appimage-extract >/dev/null) \
          || die "AppImage extract failed"
        mv "$APP_DIR/squashfs-root" "$EXTRACT_DIR"
        write_launcher "$EXTRACT_DIR/AppRun"
        ok "installed launcher $BIN_DIR/hivemind → $EXTRACT_DIR/AppRun"
      else
        warn "no AppImage produced; check electron-builder output"
      fi
    else
      warn "AppImage build failed — re-run with HIVEMIND_SKIP_APPIMAGE=1 to skip"
    fi
  fi
}

# ── claude CLI presence (warning, not fatal) ──────────────────────────────
claude_check() {
  if command -v claude >/dev/null 2>&1; then
    ok "claude → $(command -v claude)"
  else
    warn "claude CLI not found. The desktop app launches fine without it,"
    warn "but spawning a Claude tile will only work after you install it:"
    warn "  https://docs.claude.com/en/docs/claude-code"
  fi
}

# ── run ───────────────────────────────────────────────────────────────────
say "mode: $MODE"
if [ "$MODE" = "dev" ]; then
  install_dev
else
  install_prebuilt
fi
claude_check

case ":$PATH:" in
  *":$BIN_DIR:"*) ok "$BIN_DIR already on PATH" ;;
  *) warn "$BIN_DIR is NOT on PATH — add to ~/.bashrc / ~/.zshrc:"
     printf '\n    export PATH="%s:$PATH"\n\n' "$BIN_DIR"
     ;;
esac

# ── next steps ────────────────────────────────────────────────────────────
cat <<EOF

${GREEN}✓ hivemind ready.${NC}

  ${BLUE}1. Initialize a workspace in any git repo:${NC}
     cd ~/my-project
     hive init --prefix MYP
     hive init --agentic              # adds .mcp.json + claude skill + CLAUDE.md

  ${BLUE}2. Create your first issue:${NC}
     hive new "Fix token expiry"

  ${BLUE}3. Launch the desktop app:${NC}
     hivemind .

  ${BLUE}4. Upgrade in place anytime:${NC}
     bash <(curl -fsSL https://raw.githubusercontent.com/$REPO/main/install.sh)
EOF
