#!/usr/bin/env bash
# The phone's Rust core for the Android app (docs/design/phone-app-2026-10-02.md §2): the facade,
# crates/hive-phone-ffi, built for arm64-v8a (phones) and x86_64 (the emulator) through cargo-ndk;
# its Kotlin bindings, generated by the facade's own scripts/phone/bindings.sh from its build for
# this machine; and that build too, which the app's unit tests load as the app loads the core.
#
#   scripts/phone/build-android.sh <out>
#     <out>/jniLibs/<abi>/libhive_phone_ffi.so
#     <out>/kotlin/com/hivemind/phone/core/…
#     <out>/host/libhive_phone_ffi.so
#
# Gradle's buildCore task runs it before every build of apps/android (`-PskipCore` reuses the last
# output), with ANDROID_NDK_HOME set to the NDK the app is built with. By hand, set ANDROID_NDK_HOME,
# or ANDROID_HOME with an NDK under it. PHONE_ABIS names fewer ABIs for a quicker build
# (`PHONE_ABIS=x86_64`; Gradle's `-PcoreAbis=x86_64`).
set -euo pipefail

out="${1:?usage: scripts/phone/build-android.sh <out-dir>}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
crate="$root/crates/hive-phone-ffi"
target="${CARGO_TARGET_DIR:-$crate/target}"
case "$(uname -s)" in
  Darwin) host_lib="libhive_phone_ffi.dylib" ;;
  *) host_lib="libhive_phone_ffi.so" ;;
esac
abis=()
for abi in ${PHONE_ABIS:-arm64-v8a x86_64}; do abis+=(-t "$abi"); done
mkdir -p "$out"
out="$(cd "$out" && pwd)"

# From the crate's own folder: cargo-ndk reads the Cargo.toml where it runs, whatever
# --manifest-path says.
cd "$crate"

# The app's ABIs, linked for its minSdk (29), in the facade's `mobile` profile (release, no LTO).
rm -rf "$out/jniLibs"
cargo ndk --platform 29 "${abis[@]}" -o "$out/jniLibs" build --locked --lib --profile mobile
# cargo-ndk copies every library the build made, a dependency's own (iroh's) among them; the
# facade's has all it needs linked in, so it ships alone.
find "$out/jniLibs" -name '*.so' ! -name libhive_phone_ffi.so -delete

# The bindings, from the same declarations built for this machine.
rm -rf "$out/kotlin"
"$root/scripts/phone/bindings.sh" "$out/kotlin"

mkdir -p "$out/host"
cp "$target/debug/$host_lib" "$out/host/"
