#!/usr/bin/env bash
# The phone's Rust core for the Android app (docs/design/phone-app-2026-10-02.md §2): the facade,
# crates/hive-phone-ffi, built for arm64-v8a (phones) and x86_64 (the emulator) through cargo-ndk,
# and its Kotlin bindings, generated by the facade's own uniffi-bindgen from a build of the same
# crate for this machine, the one the bindgen can open.
#
#   scripts/phone/build-android.sh <out>
#     <out>/jniLibs/<abi>/libhive_phone_ffi.so
#     <out>/kotlin/com/hivemind/phone/core/…
#
# Gradle's buildCore task runs it before every build of apps/android (`-PskipCore` reuses the last
# output), with ANDROID_NDK_HOME set to the NDK the app is built with. By hand, set ANDROID_NDK_HOME,
# or ANDROID_HOME with an NDK under it.
set -euo pipefail

out="${1:?usage: scripts/phone/build-android.sh <out-dir>}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
manifest="$root/crates/hive-phone-ffi/Cargo.toml"
target="${CARGO_TARGET_DIR:-$root/crates/hive-phone-ffi/target}"
case "$(uname -s)" in
  Darwin) host_lib="libhive_phone_ffi.dylib" ;;
  *) host_lib="libhive_phone_ffi.so" ;;
esac
mkdir -p "$out"
out="$(cd "$out" && pwd)"

# The app's two ABIs, linked for its minSdk (29), in the facade's `mobile` profile (release, no LTO).
rm -rf "$out/jniLibs"
cargo ndk --manifest-path "$manifest" --platform 29 -t arm64-v8a -t x86_64 -o "$out/jniLibs" \
  build --locked --lib --profile mobile

# The bindings: the same declarations, read from this machine's build.
rm -rf "$out/kotlin"
cargo build --manifest-path "$manifest" --locked --lib
cargo run --manifest-path "$manifest" --locked --features bindgen --bin uniffi-bindgen -- \
  generate "$target/debug/$host_lib" --language kotlin --no-format --out-dir "$out/kotlin"
