# JNA finds its own classes, and the structures and callbacks it fills, by reflection.
-keep class com.sun.jna.** { *; }
-keep class * implements com.sun.jna.** { *; }
-dontwarn java.awt.**

# The core's bindings (generated by UniFFI): the native functions JNA registers by name, and the
# classes it builds and calls back into.
-keep class com.hivemind.phone.core.** { *; }
