/**
 * The PreToolUse permission-broker hook — emitted to disk as
 * `hcp-approval-hook.cjs`, run by `claude` (electron-as-node) BEFORE a tool call
 * on a SUPERVISED worker. Instead of the human approving in the terminal, the
 * request is brokered to the agent that spawned this worker (its parent), which
 * answers via `hive_approve`. The parent's decision becomes claude's
 * `permissionDecision`.
 *
 * Self-contained CommonJS, zero deps (raw string, like stopHookSource). Speaks
 * the HCP req/res wire protocol over the control-plane socket.
 *   - stdin  : the PreToolUse event JSON ({ tool_name, tool_input, cwd, … }).
 *   - argv[2]: the HCP unix socket path.
 *   - env HIVEMIND_TILE : this worker's tile id (→ its parent is looked up).
 *   - env HCP_TOKEN     : the capability token (authorizes the req).
 *   - env HIVE_SUPERVISE: "all" or a comma-list of brokered tool names. Only
 *                         these tools are brokered; everything else passes to the
 *                         normal permission flow (no round-trip).
 *   - stdout (exit 0):
 *       allow → {hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"allow"}}
 *       deny  → {…,permissionDecision:"deny",permissionDecisionReason:<reason>}
 *       (nothing) → falls through to claude's NORMAL permission flow.
 *
 * FAIL-SAFE: any error / timeout / unsupervised tool / no parent prints NOTHING,
 * so the worker just gets its normal permission prompt — never a silent allow.
 */
export function approvalHookSource(): string {
  return `// auto-generated by hivemind pty-daemon — HCP permission broker hook.
const net = require("net");
function out(obj) { try { if (obj) process.stdout.write(JSON.stringify(obj)); } catch (e) {} process.exit(0); }
function flow() { out(null); } // no output → claude's normal permission flow (fail-safe)
const sock = process.argv[2];
const token = process.env.HCP_TOKEN || "";
const tileId = process.env.HIVEMIND_TILE || "";
const sup = (process.env.HIVE_SUPERVISE || "").trim();
if (!sock || !tileId || !sup) { flow(); }
const all = sup === "all";
const set = all ? null : new Set(sup.split(",").map((s) => s.trim()).filter(Boolean));
let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (d) => { input += d; });
process.stdin.on("error", () => flow());
process.stdin.on("end", () => {
  let evt = {};
  try { evt = JSON.parse(input); } catch (e) { return flow(); }
  const tool = evt && evt.tool_name;
  if (!tool || (!all && !set.has(tool))) return flow(); // not brokered → normal flow
  const toolInput = (evt && evt.tool_input) || {};
  let settled = false;
  const done = (obj) => { if (settled) return; settled = true; out(obj); };
  const id = "ap_" + Date.now() + "_" + Math.floor(Math.random() * 1e9);
  // Generous ceiling (< the hook's own timeout): no decision → normal prompt.
  const t = setTimeout(() => done(null), 9 * 60 * 1000); if (t.unref) t.unref();
  try {
    const c = net.connect(sock, () => {
      try {
        c.write(JSON.stringify({ t: "req", id: id, method: "agent.await_approval", token: token,
          params: { callerTile: tileId, tool_name: tool, tool_input: toolInput } }) + "\\n");
      } catch (e) { done(null); }
    });
    c.setEncoding("utf8");
    let buf = "";
    c.on("data", (chunk) => {
      buf += chunk;
      let nl;
      while ((nl = buf.indexOf("\\n")) >= 0) {
        const line = buf.slice(0, nl); buf = buf.slice(nl + 1);
        let msg; try { msg = JSON.parse(line); } catch (e) { continue; }
        if (!msg || msg.t !== "res" || msg.id !== id) continue; // ignore hello/other
        try { c.end(); } catch (e) {}
        if (msg.ok && msg.result) {
          const d = msg.result.decision;
          if (d === "allow") return done({ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "allow" } });
          if (d === "deny") return done({ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: msg.result.reason || "Denied by supervising agent." } });
        }
        return done(null); // "ask" / error → normal flow
      }
    });
    c.on("error", () => done(null));
    c.on("close", () => done(null));
  } catch (e) { done(null); }
});
`;
}
