/**
 * Factory for fire-and-forget claude hook scripts that report a lifecycle EVENT
 * to the HCP socket. Three hooks share this exact skeleton — `Stop` (turn done),
 * `SubagentStart/Stop` (background work), and `Notification` (needs-you) — so the
 * connect / write-one-event / fail-open plumbing lives here ONCE. Only the event
 * `topic` and the stdin→data mapping differ per hook.
 *
 * The generated script is self-contained CommonJS, zero deps (a raw string, run
 * by `claude` as electron-as-node via a `.cjs` path). Contract:
 *   - stdin  : the hook event JSON (shape varies by hook).
 *   - argv[2]: the HCP unix socket path.
 *   - env HIVEMIND_TILE: the agent tile id (event attribution).
 * Fail-open: a missing socket/tile, a JSON parse error, a thrown mapper, or a
 * null mapper result all exit 0 WITHOUT sending — the agent proceeds normally
 * and callers fall back to the screen-scrape.
 *
 * `mapBody` is the body of `function(evt, tileId){ … }`: it has the parsed event
 * `evt` and the `tileId` in scope and must `return` the event `data` object, or
 * `null`/`undefined` to skip sending (e.g. an unrecognized phase). It runs inside
 * the generated CJS, so it must be self-contained ES5-ish (no imports, no deps).
 */
export function eventHookSource(topic: string, mapBody: string): string {
  return `// auto-generated by hivemind pty-daemon — HCP ${topic} event reporter.
const net = require("net");
function done() { try { process.exit(0); } catch (e) {} }
const sock = process.argv[2];
const tileId = process.env.HIVEMIND_TILE || "";
if (!sock || !tileId) { done(); }
let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (d) => { input += d; });
process.stdin.on("error", () => done());
process.stdin.on("end", () => {
  let evt = {};
  try { evt = JSON.parse(input); } catch (e) {}
  let data;
  try { data = (function (evt, tileId) { ${mapBody} })(evt, tileId); } catch (e) { return done(); }
  if (data == null) return done();
  let settled = false;
  const fin = () => { if (settled) return; settled = true; done(); };
  const t = setTimeout(fin, 1500); if (t.unref) t.unref();
  try {
    const c = net.connect(sock, () => {
      try { c.write(JSON.stringify({ t: "event", topic: ${JSON.stringify(topic)}, data: data }) + "\\n"); } catch (e) {}
      try { c.end(); } catch (e) {}
    });
    c.on("error", fin);
    c.on("close", fin);
  } catch (e) { fin(); }
});
`;
}
