/**
 * The kiro `preToolUse` permission-broker hook — emitted to disk as
 * `hcp-kiro-approval-hook.cjs`, run by `kiro-cli` (electron-as-node) BEFORE a
 * tool call. Brokers a SUPERVISED kiro worker's tool-permission decisions to
 * the agent that spawned it (its parent), which answers via `hive_approve` —
 * same `agent.await_approval` req/res wire protocol as claude's
 * `hcp-approval-hook.cjs` (see approval-hook-source.ts).
 *
 * The CONTRACT differs from claude's, though (docs/cli/reference/exit-codes,
 * cited in the maintainer's audit): kiro's `preToolUse` blocks a tool by EXIT
 * CODE 2 with the reason on stderr — there is no claude-style
 * `permissionDecision:"allow"` JSON that authoritatively bypasses kiro's OWN
 * per-tool prompt. So this hook can DENY a brokered tool deterministically
 * (exit 2 — kiro blocks the call and feeds the stderr reason back to the
 * model), but an "allow" decision can only exit 0 (don't object) — whether
 * that ALSO suppresses kiro's own confirmation prompt for a tool outside its
 * `allowedTools`/trust set is UNVERIFIED (no kiro-cli binary available to
 * confirm). Flagged in the PR description's lifecycle table: supervise on kiro
 * denies authoritatively; an "allow" may still need the tool independently
 * trusted by kiro itself to avoid a second, un-brokered prompt.
 *
 * Self-contained CommonJS, zero deps, same shape as approval-hook-source.ts:
 *   - stdin  : the preToolUse event JSON ({ tool_name, tool_input, cwd, … }).
 *   - argv[2]: the HCP unix socket path.
 *   - env HIVEMIND_TILE : this worker's tile id (→ its parent is looked up).
 *   - env HCP_TOKEN     : the capability token (authorizes the req).
 *   - env HIVE_SUPERVISE: "all" or a comma-list of brokered tool names,
 *                         INHERITED from the spawned kiro process's own env
 *                         (this hook command carries no baked env — the config
 *                         file is shared across all kiro tiles; see
 *                         kiro-resume.ts's module docblock). Only these tools
 *                         are brokered; everything else exits 0 (kiro's normal
 *                         flow, whatever that is for the tool).
 *
 * FAIL-SAFE: any error / timeout / unsupervised tool / no parent / "allow" /
 * "ask" all exit 0 (don't block) — never a silent, unbounded deny.
 */
export function kiroApprovalHookSource(): string {
  return `// auto-generated by hivemind pty-daemon — kiro PreToolUse permission broker.
const net = require("net");
function allow() { try { process.exit(0); } catch (e) {} }
function deny(reason) {
  try { process.stderr.write(String(reason || "Denied by supervising agent.")); } catch (e) {}
  try { process.exitCode = 2; } catch (e) {}
  try { process.exit(2); } catch (e) {}
}
const sock = process.argv[2];
const token = process.env.HCP_TOKEN || "";
const tileId = process.env.HIVEMIND_TILE || "";
const sup = (process.env.HIVE_SUPERVISE || "").trim();
if (!sock || !tileId || !sup) { allow(); }
const all = sup === "all";
const set = all ? null : new Set(sup.split(",").map((s) => s.trim()).filter(Boolean));
let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (d) => { input += d; });
process.stdin.on("error", () => allow());
process.stdin.on("end", () => {
  let evt = {};
  try { evt = JSON.parse(input); } catch (e) { return allow(); }
  const tool = evt && evt.tool_name;
  if (!tool || (!all && !set.has(tool))) return allow(); // not brokered → don't block
  const toolInput = (evt && evt.tool_input) || {};
  let settled = false;
  const done = (fn) => { if (settled) return; settled = true; fn(); };
  const id = "ap_" + Date.now() + "_" + Math.floor(Math.random() * 1e9);
  // Generous ceiling (< the hook's own timeout): no decision → don't block.
  const t = setTimeout(() => done(allow), 9 * 60 * 1000); if (t.unref) t.unref();
  try {
    const c = net.connect(sock, () => {
      try {
        c.write(JSON.stringify({ t: "req", id: id, method: "agent.await_approval", token: token,
          params: { callerTile: tileId, tool_name: tool, tool_input: toolInput } }) + "\\n");
      } catch (e) { done(allow); }
    });
    c.setEncoding("utf8");
    let buf = "";
    c.on("data", (chunk) => {
      buf += chunk;
      let nl;
      while ((nl = buf.indexOf("\\n")) >= 0) {
        const line = buf.slice(0, nl); buf = buf.slice(nl + 1);
        let msg; try { msg = JSON.parse(line); } catch (e) { continue; }
        if (!msg || msg.t !== "res" || msg.id !== id) continue; // ignore hello/other
        try { c.end(); } catch (e) {}
        if (msg.ok && msg.result) {
          const d = msg.result.decision;
          if (d === "deny") return done(() => deny(msg.result.reason));
          // "allow" / "ask" / anything else → don't block (see docblock: kiro
          // has no authoritative allow signal, unlike claude).
        }
        return done(allow);
      }
    });
    c.on("error", () => done(allow));
    c.on("close", () => done(allow));
  } catch (e) { done(allow); }
});
`;
}
