/**
 * The pi lifecycle-bridge + orchestration extension source — emitted to disk as
 * `hive-pi-ext.mjs` and loaded by `pi -e <path>`. pi has no claude-style hook
 * system, but it DOES expose an extension API (`export default function (pi) {
 * pi.on(event, handler); pi.registerTool(...) }`), so we bridge pi's lifecycle
 * events to the HCP socket the same way claude's Stop hook does — AND give a pi
 * worker the same orchestration + supervise powers claude gets from the hive MCP
 * server, but over the HCP socket directly (no MCP dependency).
 *
 * The generated module is self-contained ESM: its ONLY runtime imports are
 * `node:net` and `typebox` (pi bundles typebox and exposes it to extensions —
 * see the pi extension types: `import type { Static, TSchema } from "typebox"`).
 * No bundler / no hivemind imports, so it runs inside pi's own process. It reads
 * `HIVE_HCP_SOCK` + `HCP_TOKEN` + `HIVEMIND_TILE` (+ optional `HIVE_SUPERVISE`)
 * from env; it no-ops (stays a plain pi session) unless hivemind injected the
 * socket + tile.
 *
 * Three capabilities, all fail-open (never throw out of a handler, never hang pi):
 *   1. LIFECYCLE BRIDGE (fire-and-forget events):
 *        - `agent_start`  → status working  (turn START)
 *        - `message_end`  → accumulate the assistant reply text (inline reply)
 *        - `agent_end`    → turn (with inline text) + status idle  (turn END; the
 *                           claude-Stop equivalent). pi writes no transcript path,
 *                           so the reply rides the event itself, read by agent.read.
 *   2. SUPERVISE (permission brokering): a `tool_call` handler routes brokered
 *      tools to the supervisor via `agent.await_approval` (req/res). "deny" blocks
 *      the tool; allow/ask/timeout/any error → fail-open (allow).
 *   3. ORCHESTRATION TOOLS: `hive_spawn_agent` / `hive_read` / `hive_send` /
 *      `hive_list_tiles` / `hive_workflow` / `hive_approve`, registered so pi's LLM
 *      can drive other agents. Each makes a token-authenticated HCP req/res call.
 *
 * TYPE-CHECKING: the API surface this string uses is statically asserted against
 * pi's official `@earendil-works/pi-coding-agent` types in the typecheck-only
 * companion `hive-pi-ext.types.ts` — so a pi API rename (event name, `registerTool`
 * / `tool_call` shape, tool-result shape) fails `tsc`. The companion is never
 * imported at runtime; this file ships a plain-JS string (pi loads it as `.mjs`,
 * so it must be valid JS — no TS syntax, no `import type`).
 */
export function piExtSource(): string {
  return `// auto-generated by hivemind — pi lifecycle → HCP bridge + supervise + native hive orchestration tools.
// Loaded via \`pi -e <this file>\`; no-ops unless hivemind injected HIVE_HCP_SOCK + HIVEMIND_TILE.
// Self-contained: only \`node:net\` + \`typebox\` (typebox is bundled with pi at runtime).
import net from "node:net";
import { Type } from "typebox";

export default function (pi) {
  const sock = process.env.HIVE_HCP_SOCK;
  const tile = process.env.HIVEMIND_TILE;
  const token = process.env.HCP_TOKEN;
  if (!sock || !tile) return; // not spawned by hivemind → stay a plain pi session

  // ── lifecycle bridge: fire-and-forget HCP event (connect, write one line, close) ──
  const post = (topic, data) => {
    try {
      const c = net.connect(sock, () => {
        try { c.write(JSON.stringify({ t: "event", topic: topic, data: data }) + "\\n"); } catch (e) {}
        try { c.end(); } catch (e) {}
      });
      c.on("error", () => {});
    } catch (e) {}
  };

  const textOf = (m) => {
    if (!m) return "";
    const c = m.content;
    if (typeof c === "string") return c;
    if (Array.isArray(c)) return c.filter((b) => b && b.type === "text").map((b) => b.text || "").join("");
    return "";
  };

  let lastText = "";
  pi.on("agent_start", async () => { lastText = ""; post("status", { tileId: tile, state: "working" }); });
  pi.on("message_end", async (event) => {
    const m = event && event.message;
    if (m && m.role === "assistant") { const t = textOf(m); if (t) lastText = t; }
  });
  pi.on("agent_end", async (event) => {
    // Prefer the accumulated assistant text; fall back to the last assistant message in event.messages.
    let text = lastText;
    if (!text && event && Array.isArray(event.messages)) {
      for (let i = event.messages.length - 1; i >= 0; i--) {
        const m = event.messages[i];
        if (m && m.role === "assistant") { const t = textOf(m); if (t) { text = t; break; } }
      }
    }
    post("turn", { tileId: tile, text: text || "" });
    post("status", { tileId: tile, state: "idle" });
  });

  // ── HCP request/response client (token-authenticated, line-framed). Resolves
  //    { ok, result } | { ok:false, error } | null. NEVER rejects, NEVER hangs:
  //    any socket error / close / parse failure / timeout / abort → resolve(null)
  //    so callers can fail open. \`id\` is a monotonic counter + this tile id. ──
  let reqCounter = 0;
  const hcpRequest = (method, params, signal, timeoutMs) => new Promise((resolve) => {
    let settled = false;
    let c = null;
    let timer = null;
    const done = (v) => {
      if (settled) return;
      settled = true;
      if (timer) { try { clearTimeout(timer); } catch (e) {} }
      try { if (c) c.end(); } catch (e) {}
      resolve(v);
    };
    const id = "pi_" + tile + "_" + (++reqCounter);
    try {
      c = net.connect(sock, () => {
        try {
          c.write(JSON.stringify({ t: "req", id: id, method: method, params: params, token: token }) + "\\n");
        } catch (e) { done(null); }
      });
    } catch (e) { resolve(null); return; }
    let buf = "";
    c.on("data", (d) => {
      buf += d.toString("utf8");
      let nl;
      while ((nl = buf.indexOf("\\n")) >= 0) {
        const line = buf.slice(0, nl);
        buf = buf.slice(nl + 1);
        if (!line) continue;
        let msg;
        try { msg = JSON.parse(line); } catch (e) { continue; }
        if (msg && msg.t === "res" && msg.id === id) {
          done(msg.ok ? { ok: true, result: msg.result } : { ok: false, error: msg.error });
          return;
        }
      }
    });
    c.on("error", () => done(null));
    c.on("close", () => done(null));
    timer = setTimeout(() => done(null), timeoutMs);
    if (timer && typeof timer.unref === "function") timer.unref();
    if (signal) {
      if (signal.aborted) done(null);
      else { try { signal.addEventListener("abort", () => done(null), { once: true }); } catch (e) {} }
    }
  });

  // ── SUPERVISE (permission brokering) ──────────────────────────────────────
  // HIVE_SUPERVISE is injected into a supervised tile's env by ptySpawn (main).
  // "all" → broker every tool; else a comma-list of tool names (case-insensitive,
  // pi tool names are lowercase: bash/read/write/edit/…). A brokered tool routes
  // to the supervisor via agent.await_approval; only "deny" blocks — allow / ask /
  // timeout / any error fails OPEN so pi never hangs. Give the wait ~9.5 min
  // (slightly over the main-side APPROVAL_TIMEOUT_MS) so a lost response fails open.
  const superviseSpec = (process.env.HIVE_SUPERVISE || "").trim();
  if (superviseSpec) {
    const brokerAll = superviseSpec.toLowerCase() === "all";
    const brokerList = brokerAll
      ? null
      : superviseSpec.split(",").map((s) => s.trim().toLowerCase()).filter(Boolean);
    const APPROVAL_WAIT_MS = 9.5 * 60 * 1000;
    pi.on("tool_call", async (event, ctx) => {
      const name = String((event && event.toolName) || "");
      if (!name) return; // allow
      if (!brokerAll && !(brokerList && brokerList.indexOf(name.toLowerCase()) >= 0)) return; // not brokered → allow
      const res = await hcpRequest(
        "agent.await_approval",
        { callerTile: tile, tool_name: name, tool_input: (event && event.input) || {} },
        ctx && ctx.signal,
        APPROVAL_WAIT_MS,
      );
      if (res && res.ok && res.result && res.result.decision === "deny") {
        return { block: true, reason: (res.result.reason) || "Denied by supervisor" };
      }
      return; // allow / ask / timeout / any error → FAIL-OPEN
    });
  }

  // ── NATIVE HIVE ORCHESTRATION TOOLS ───────────────────────────────────────
  // Only when the full control-plane triple is present (socket + token + tile),
  // so a pi worker can spawn/drive/supervise other agents straight over HCP.
  if (!token) return;
  const ORCH_TIMEOUT_MS = 60 * 60 * 1000; // generous ceiling; a long workflow.run blocks main-side, not us

  const call = async (method, params, signal, timeoutMs) => {
    const r = await hcpRequest(method, params, signal, timeoutMs || ORCH_TIMEOUT_MS);
    if (r && r.ok) {
      return { content: [{ type: "text", text: JSON.stringify(r.result) }], details: r.result };
    }
    const msg = r && r.error
      ? (r.error.message || (typeof r.error === "string" ? r.error : JSON.stringify(r.error)))
      : "no response from hive control plane";
    // AgentToolResult has no isError field — encode the failure in the text + details.
    return { content: [{ type: "text", text: "hive error: " + msg }], details: { error: msg } };
  };

  const superviseParam = Type.Optional(Type.Union([Type.Boolean(), Type.String(), Type.Array(Type.String())]));

  pi.registerTool({
    name: "hive_spawn_agent",
    label: "Spawn hive agent",
    description:
      "Spawn a NEW coding agent as a tile on the hivemind canvas and hand it a prompt. Returns its tileId. Delegate a subtask to a sibling agent. By default the worker AUTO-REPORTS: its reply is delivered back into your session when it finishes a turn. Pass \`supervise\` to route the worker's tool-permission prompts to YOU (answer with hive_approve). Requires the hivemind desktop app.",
    parameters: Type.Object({
      agent: Type.Optional(Type.String({ description: "Agent to launch: 'claude' (default), 'codex', 'droid', 'pi', …" })),
      prompt: Type.Optional(Type.String({ description: "Initial task delivered once the agent is ready." })),
      frame: Type.Optional(Type.String({ description: "Frame to spawn into (id, repo/worktree name, or title). Omit to use your own frame." })),
      mode: Type.Optional(Type.String({ description: "claude permission mode. Omit → the worker runs autonomously (bypassPermissions). Pass 'plan'/'acceptEdits'/'default' to keep a human in the loop." })),
      model: Type.Optional(Type.String({ description: "claude only — model alias like 'opus' or 'sonnet'." })),
      supervise: superviseParam,
    }),
    async execute(toolCallId, params, signal) {
      return call("tile.spawn_agent", {
        agent: params.agent, prompt: params.prompt, frame: params.frame,
        mode: params.mode, model: params.model, supervise: params.supervise,
        callerTile: tile,
      }, signal);
    },
  });

  pi.registerTool({
    name: "hive_read",
    label: "Read hive agent",
    description:
      "Block until a spawned agent (by tileId) finishes its current turn, then return its reply. On timeout returns finalStatus:'timeout' (the agent is still working). Most of the time you don't need this — report:true workers auto-deliver their replies. Requires the hivemind desktop app.",
    parameters: Type.Object({
      tileId: Type.String({ description: "The worker's tileId (from hive_spawn_agent)." }),
      timeout_ms: Type.Optional(Type.Number({ description: "Max wait in ms (default 120000)." })),
    }),
    async execute(toolCallId, params, signal) {
      const p = { tileId: params.tileId };
      if (typeof params.timeout_ms === "number") p.timeoutMs = params.timeout_ms;
      return call("agent.read", p, signal);
    },
  });

  pi.registerTool({
    name: "hive_send",
    label: "Send to hive agent",
    description:
      "Send text to an agent tile (by tileId) — like typing into its terminal and pressing Enter. Use for follow-up turns in a conversation with a spawned agent. Requires the hivemind desktop app.",
    parameters: Type.Object({
      tileId: Type.String(),
      text: Type.String(),
      submit: Type.Optional(Type.Boolean({ description: "Press Enter after the text (default true)." })),
    }),
    async execute(toolCallId, params, signal) {
      const p = { tileId: params.tileId, text: params.text };
      if (typeof params.submit === "boolean") p.submit = params.submit;
      return call("agent.send", p, signal);
    },
  });

  pi.registerTool({
    name: "hive_list_tiles",
    label: "List hive tiles",
    description:
      "List the tiles on the hivemind canvas grouped by frame — returns { frames:[{ frameId, title, repo, branch, tiles:[{ tileId, kind, label, status }] }], loose:[…] }. Pass \`frame\` to filter to a single frame. Requires the hivemind desktop app.",
    parameters: Type.Object({
      frame: Type.Optional(Type.String({ description: "Filter to one frame (id, repo name, or title). Omit to list all frames." })),
    }),
    async execute(toolCallId, params, signal) {
      return call("tile.list", { frame: params.frame }, signal);
    },
  });

  pi.registerTool({
    name: "hive_approve",
    label: "Approve hive worker",
    description:
      "Answer an approval request from a supervised worker (spawned with \`supervise\`). When a worker wants to run a brokered tool you'll get a '[hive] APPROVAL — worker <id> wants to run <tool>' message with a reqId; call this with that reqId. decision: 'allow'/'deny' for this one call, or 'always'/'never' to also remember it for that worker+tool. Requires the hivemind desktop app.",
    parameters: Type.Object({
      reqId: Type.String({ description: "The approval request id from the '[hive] APPROVAL …' message." }),
      decision: Type.String({ description: "allow | deny | always | never." }),
      reason: Type.Optional(Type.String({ description: "Optional note shown to the worker (useful on deny)." })),
    }),
    async execute(toolCallId, params, signal) {
      const p = { reqId: params.reqId, decision: params.decision };
      if (typeof params.reason === "string") p.reason = params.reason;
      return call("agent.approve", p, signal);
    },
  });

  pi.registerTool({
    name: "hive_workflow",
    label: "Run hive workflow",
    description:
      "Run a MULTI-AGENT WORKFLOW: spawn a fleet of worker agents as visible tiles, drive them, and BLOCK until done — then return their replies aggregated. shape: 'fanout' (one worker per items[i], \`prompt\` is a template with {item}); 'mapreduce' (fanout then one reducer fed all outputs via \`reduce_prompt\` with {results}); 'pipeline' (sequential \`stages\`, each may use {input} for the prior stage's reply). Each worker result carries a status ('turn'|'timeout'|'error'). Requires the hivemind desktop app.",
    parameters: Type.Object({
      shape: Type.String({ description: "fanout | pipeline | mapreduce." }),
      items: Type.Optional(Type.Array(Type.String(), { description: "fanout/mapreduce: one worker per element, substituted into {item}." })),
      prompt: Type.Optional(Type.String({ description: "fanout/mapreduce: the per-worker task. Use {item}." })),
      stages: Type.Optional(Type.Array(Type.String(), { description: "pipeline: one prompt per stage. Each may use {input}." })),
      input: Type.Optional(Type.String({ description: "pipeline: optional seed for the first stage's {input}." })),
      reduce_prompt: Type.Optional(Type.String({ description: "mapreduce: the reducer prompt. Use {results}." })),
      agent: Type.Optional(Type.String({ description: "Runtime for every worker: 'claude' (default), 'codex', 'droid', 'pi', …" })),
      model: Type.Optional(Type.String({ description: "claude only — model alias applied to every worker." })),
      frame: Type.Optional(Type.String({ description: "Frame to spawn workers into. Omit to use your own frame." })),
      supervise: superviseParam,
      max_concurrent: Type.Optional(Type.Number({ description: "Max workers live at once (default 6, capped 12)." })),
      timeout_ms: Type.Optional(Type.Number({ description: "Per-worker turn ceiling in ms (default 600000)." })),
      close_when_done: Type.Optional(Type.Boolean({ description: "Close each worker tile after collecting its reply (default false)." })),
    }),
    async execute(toolCallId, params, signal) {
      return call("workflow.run", {
        shape: params.shape, items: params.items, prompt: params.prompt,
        stages: params.stages, input: params.input, reduce_prompt: params.reduce_prompt,
        agent: params.agent, model: params.model, frame: params.frame,
        supervise: params.supervise, max_concurrent: params.max_concurrent,
        timeout_ms: params.timeout_ms, close_when_done: params.close_when_done,
        callerTile: tile,
      }, signal);
    },
  });
}
`;
}
