/**
 * The pi lifecycle-bridge extension source — emitted to disk as
 * `hive-pi-ext.mjs` and loaded by `pi -e <path>`. pi has no claude-style hook
 * system, but it DOES expose an extension API (`export default function (pi) {
 * pi.on(event, handler) }`), so we bridge pi's lifecycle events to the HCP
 * socket the same way claude's Stop hook does — turning a pi tile into a
 * first-class, deterministically-tracked worker.
 *
 * The generated module is self-contained ESM (only `node:net`, no bundler / no
 * hivemind imports), so it runs inside pi's own process. It reads
 * `HIVE_HCP_SOCK` + `HIVEMIND_TILE` from env and posts HCP `status`/`turn`
 * events; it no-ops (stays a plain pi session) unless hivemind injected both.
 * Event mapping (fires once per user prompt):
 *   - `agent_start`  → status working  (turn START)
 *   - `message_end`  → accumulate the assistant reply text (inline reply)
 *   - `agent_end`    → turn (with inline text) + status idle  (turn END; the
 *                      claude-Stop equivalent). pi writes no transcript path, so
 *                      the reply rides the event itself, read back by agent.read.
 * Mirrors stop-hook-source.ts: a string generator, fail-open, never blocks pi.
 */
export function piExtSource(): string {
  return `// auto-generated by hivemind — pi lifecycle → HCP bridge (turn + status + inline reply).
// Loaded via \`pi -e <this file>\`; no-ops unless hivemind injected HIVE_HCP_SOCK + HIVEMIND_TILE.
import net from "node:net";

export default function (pi) {
  const sock = process.env.HIVE_HCP_SOCK;
  const tile = process.env.HIVEMIND_TILE;
  if (!sock || !tile) return; // not spawned by hivemind → stay a plain pi session

  const post = (topic, data) => {
    try {
      const c = net.connect(sock, () => {
        try { c.write(JSON.stringify({ t: "event", topic: topic, data: data }) + "\\n"); } catch (e) {}
        try { c.end(); } catch (e) {}
      });
      c.on("error", () => {});
    } catch (e) {}
  };

  const textOf = (m) => {
    if (!m) return "";
    const c = m.content;
    if (typeof c === "string") return c;
    if (Array.isArray(c)) return c.filter((b) => b && b.type === "text").map((b) => b.text || "").join("");
    return "";
  };

  let lastText = "";
  pi.on("agent_start", async () => { lastText = ""; post("status", { tileId: tile, state: "working" }); });
  pi.on("message_end", async (event) => {
    const m = event && event.message;
    if (m && m.role === "assistant") { const t = textOf(m); if (t) lastText = t; }
  });
  pi.on("agent_end", async (event) => {
    // Prefer the accumulated assistant text; fall back to the last assistant message in event.messages.
    let text = lastText;
    if (!text && event && Array.isArray(event.messages)) {
      for (let i = event.messages.length - 1; i >= 0; i--) {
        const m = event.messages[i];
        if (m && m.role === "assistant") { const t = textOf(m); if (t) { text = t; break; } }
      }
    }
    post("turn", { tileId: tile, text: text || "" });
    post("status", { tileId: tile, state: "idle" });
  });
}
`;
}
