/**
 * The `Stop` hook script source — emitted to disk as `hcp-stop-hook.cjs`, run by
 * `claude` (electron-as-node) when an agent FINISHES A TURN. It reports the
 * finished turn (+ transcript path) to the HCP socket so a driver blocked in
 * agent.read can wake deterministically and read the agent's reply. It does NOT
 * block the stop (no stdout, exit 0) — the agent stops normally.
 *
 * Self-contained CommonJS, zero deps (raw string, like trackerSource()).
 *   - stdin  : the Stop event JSON ({ transcript_path, session_id, stop_hook_active }).
 *   - argv[2]: the HCP unix socket path.
 *   - env HIVEMIND_TILE: the agent tile id.
 * Fail-open: any error → exit 0 (the turn still ends; agent.read falls back to
 * its timeout).
 */
export function stopHookSource(): string {
  return `// auto-generated by hivemind pty-daemon — HCP turn-completion reporter.
const net = require("net");
function done() { try { process.exit(0); } catch (e) {} }
const sock = process.argv[2];
const tileId = process.env.HIVEMIND_TILE || "";
if (!sock || !tileId) { done(); }
let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (d) => { input += d; });
process.stdin.on("error", () => done());
process.stdin.on("end", () => {
  let evt = {};
  try { evt = JSON.parse(input); } catch (e) {}
  const transcriptPath = (evt && evt.transcript_path) || null;
  let settled = false;
  const fin = () => { if (settled) return; settled = true; done(); };
  // Don't hang the turn if the app is unreachable.
  const t = setTimeout(fin, 1500); if (t.unref) t.unref();
  try {
    const c = net.connect(sock, () => {
      try { c.write(JSON.stringify({ t: "event", topic: "turn", data: { tileId: tileId, transcriptPath: transcriptPath } }) + "\\n"); } catch (e) {}
      try { c.end(); } catch (e) {}
    });
    c.on("error", fin);
    c.on("close", fin);
  } catch (e) { fin(); }
});
`;
}
