/**
 * Per-tile live-session store — records, for each claude tile, the session id
 * it's CURRENTLY in (which can change when the user `/resume`s another session
 * or claude reassigns its id). On reboot-restore the daemon resumes the tracked
 * id rather than the originally-spawned one.
 *
 * Why per-FILE, not one shared map: claude's SessionStart hook fires once per
 * tile, and on app restart EVERY frame's claude tile starts at the same time.
 * The previous design had each hook do an unsynchronized read-modify-write on a
 * single `tile-sessions.json` through one fixed `.tmp` path — concurrent writers
 * lost each other's updates (and could corrupt the file), so with 2+ frames a
 * tile's tracked id silently vanished and resume fell back to a stale/wrong
 * session. Giving every tile its OWN file removes the shared state entirely:
 * no read-modify-write, a per-process tmp name, writers never collide.
 *
 * This module is electron-free so it's unit-testable. `trackerSource()` returns
 * the standalone `.cjs` the daemon writes to disk for claude's hook to exec
 * (the hook runs in claude's environment and can't import this module, so its
 * write logic is inlined there — keep it in sync with `writeTrackedSession`).
 */
import fs from "node:fs";
import path from "node:path";

/** The per-tile file path. base64url so any tile id (incl. `:`) is path-safe. */
export function tileSessionFile(dir: string, tileId: string): string {
  return path.join(dir, Buffer.from(tileId).toString("base64url") + ".json");
}

/** Race-safe write of one tile's live session id. Per-tile file + unique tmp,
 *  so concurrent writers for DIFFERENT tiles never touch the same path, and
 *  there is no shared map to lose-update. No-ops when the value is unchanged. */
export function writeTrackedSession(dir: string, tileId: string, sessionId: string): void {
  const out = tileSessionFile(dir, tileId);
  try {
    if ((JSON.parse(fs.readFileSync(out, "utf8")) || {}).session_id === sessionId) return;
  } catch {
    /* missing / unreadable → (re)write below */
  }
  fs.mkdirSync(dir, { recursive: true });
  const tmp = `${out}.${process.pid}.${Date.now()}.${Math.random().toString(36).slice(2)}.tmp`;
  fs.writeFileSync(tmp, JSON.stringify({ session_id: sessionId }));
  fs.renameSync(tmp, out);
}

/** Read a tile's tracked session id. Falls back to a legacy shared-map file
 *  (the old `tile-sessions.json`) so ids recorded before this change still
 *  resume until the tile re-tracks on its next SessionStart. */
export function readTrackedSession(
  dir: string,
  tileId: string,
  legacyMapFile?: string,
): string | undefined {
  try {
    const v = JSON.parse(fs.readFileSync(tileSessionFile(dir, tileId), "utf8"));
    if (v && typeof v.session_id === "string") return v.session_id;
  } catch {
    /* no per-tile file → try legacy */
  }
  if (legacyMapFile) {
    try {
      const map = JSON.parse(fs.readFileSync(legacyMapFile, "utf8"));
      const v = map?.[tileId];
      if (typeof v === "string") return v;
    } catch {
      /* no legacy map */
    }
  }
  return undefined;
}

/** Drop a tile's tracked-session file (called when its session is killed). */
export function evictTrackedSession(dir: string, tileId: string): void {
  try {
    fs.unlinkSync(tileSessionFile(dir, tileId));
  } catch {
    /* already gone */
  }
}

/** Standalone `.cjs` source for claude's SessionStart hook. argv[2] is the
 *  per-tile directory; $HIVEMIND_TILE is the tile id; stdin is the hook JSON
 *  (carries `session_id`). Inlines the same per-tile write as
 *  `writeTrackedSession` — keep the two in sync. */
export function trackerSource(): string {
  return `// auto-generated by hivemind pty-daemon — records claude's live session id.
const fs = require("fs");
const path = require("path");
let input = "";
process.stdin.on("data", (d) => { input += d; });
process.stdin.on("end", () => {
  try {
    const tile = process.env.HIVEMIND_TILE;
    const dir = process.argv[2];
    if (!tile || !dir) return;
    const sid = (JSON.parse(input || "{}") || {}).session_id;
    if (!sid) return;
    const out = path.join(dir, Buffer.from(tile).toString("base64url") + ".json");
    try { if ((JSON.parse(fs.readFileSync(out, "utf8")) || {}).session_id === sid) return; } catch {}
    fs.mkdirSync(dir, { recursive: true });
    const tmp = out + "." + process.pid + "." + Date.now() + "." + Math.random().toString(36).slice(2) + ".tmp";
    fs.writeFileSync(tmp, JSON.stringify({ session_id: sid }));
    fs.renameSync(tmp, out);
  } catch {}
});
`;
}
