/**
 * The PreToolUse(ExitPlanMode) hook script source — emitted to disk by the
 * daemon as `plan-review-hook.cjs` and run by `claude` (as electron-as-node)
 * when the agent hands off a plan. It is the bridge between Claude Code's hook
 * protocol and the running hivemind app.
 *
 * Self-contained CommonJS, ZERO dependencies (it runs in a bare node context,
 * not the bundle — so it's authored as a raw string, exactly like
 * `trackerSource()` in tile-session-store.ts). Contract (verified against
 * current Claude Code docs):
 *   - stdin  : the PreToolUse event JSON; the plan markdown is `tool_input.plan`.
 *   - argv[2]: the plan-bridge unix socket path (injected via the hook command).
 *   - env HIVEMIND_TILE: the agent tile id (so the app opens the review next to
 *     the right terminal).
 *   - stdout (exit 0):
 *       approve → {hookSpecificOutput:{hookEventName:"PreToolUse",
 *                  permissionDecision:"allow"}}
 *       deny    → {...,permissionDecision:"deny",
 *                  permissionDecisionReason:<feedback markdown>}
 *
 * FAIL-OPEN: any error (app closed, socket gone, malformed reply) prints
 * `allow`, so a missing review UI never bricks the agent — the plan just
 * proceeds as if no hook were installed.
 */

export function planHookSource(): string {
  return `// auto-generated by hivemind pty-daemon — in-canvas plan review hook.
const net = require("net");
const ALLOW = JSON.stringify({ hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "allow" } });
function allow() { try { process.stdout.write(ALLOW); } catch (e) {} process.exit(0); }
function deny(reason) {
  try {
    process.stdout.write(JSON.stringify({
      hookSpecificOutput: { hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: reason || "Changes requested." },
    }));
  } catch (e) {}
  process.exit(0);
}
const sock = process.argv[2];
const tileId = process.env.HIVEMIND_TILE || "";
if (!sock) { allow(); }
let input = "";
process.stdin.setEncoding("utf8");
process.stdin.on("data", (d) => { input += d; });
process.stdin.on("error", () => allow());
process.stdin.on("end", () => {
  let evt;
  try { evt = JSON.parse(input); } catch (e) { return allow(); }
  const plan = evt && evt.tool_input && evt.tool_input.plan;
  const cwd = (evt && evt.cwd) || process.cwd();
  if (!plan || typeof plan !== "string") return allow();
  let settled = false;
  const done = (fn, arg) => { if (settled) return; settled = true; fn(arg); };
  const client = net.connect(sock, () => {
    try { client.write(JSON.stringify({ tileId: tileId, plan: plan, cwd: cwd }) + "\\n"); }
    catch (e) { done(allow); }
  });
  client.setEncoding("utf8");
  client.on("error", () => done(allow));
  let buf = "";
  client.on("data", (chunk) => {
    buf += chunk;
    const nl = buf.indexOf("\\n");
    if (nl < 0) return;
    let res;
    try { res = JSON.parse(buf.slice(0, nl)); } catch (e) { return done(allow); }
    try { client.end(); } catch (e) {}
    if (res && res.decision === "deny") return done(deny, res.feedback);
    return done(allow);
  });
  client.on("close", () => done(allow));
});
`;
}
