/**
 * PTY daemon — a long-lived process the Electron main spawns (via
 * ELECTRON_RUN_AS_NODE) so terminal sessions survive the window closing.
 * Owns all node-pty sessions through SessionManager and speaks NDJSON over a
 * Unix domain socket. See research/persistence-plan.md.
 *
 * Spawned as: electron <this> <socketPath>  with ELECTRON_RUN_AS_NODE=1.
 */
import net from "node:net";
import fs from "node:fs";
import path from "node:path";
import { randomUUID } from "node:crypto";
import * as pty from "@lydell/node-pty";
import { SessionManager, type ManagedPty, type SpawnSpec, type SessionSnapshot } from "./pty-session-manager.js";
import { type ClientMsg, type ServerMsg, frame, makeLineDecoder } from "./pty-protocol.js";

const socketPath = process.argv[2] || process.env.HIVEMIND_PTY_SOCK;
if (!socketPath) {
  console.error("[pty-daemon] no socket path given");
  process.exit(1);
}

// Disk snapshots — survive daemon death + OS reboot. Stored next to the socket
// under <userData>/sessions/<base64url-id>.json. The PTY itself can't be
// reconstructed across reboot, but the VISIBLE STATE can: on first attach,
// the daemon replays the snapshot AND spawns a fresh PTY with the stored spec
// so the user sees their last screen + a working shell taking over.
const sessionsDir = path.join(path.dirname(socketPath), "sessions");
try { fs.mkdirSync(sessionsDir, { recursive: true }); } catch { /* ignore */ }

// ── live claude session tracking ───────────────────────────────────────────
// hivemind spawns `claude --session-id <uuid>`, but the user can switch the
// ACTIVE session inside the tile (`/resume`, `--continue`, claude reassigning
// its id). To resume what the tile is ACTUALLY in, we inject a merged
// SessionStart hook (fires on start/resume/clear) that records
// tileId → live session_id into tile-sessions.json. On restore we prefer that
// tracked id over the originally-injected one. The hook command bakes in the
// tile id (HIVEMIND_TILE) so it's correct even with several claude tiles in one
// cwd. The tracker runs as electron-as-node (.cjs forces CommonJS).
const userDataDir = path.dirname(socketPath);
const tileSessionsPath = path.join(userDataDir, "tile-sessions.json");
const trackerPath = path.join(userDataDir, "tile-session-tracker.cjs");
const TRACKER_SRC = `// auto-generated by hivemind pty-daemon — records claude's live session id.
const fs = require("fs");
let input = "";
process.stdin.on("data", (d) => { input += d; });
process.stdin.on("end", () => {
  try {
    const tile = process.env.HIVEMIND_TILE;
    const out = process.argv[2];
    if (!tile || !out) return;
    const sid = (JSON.parse(input || "{}") || {}).session_id;
    if (!sid) return;
    let map = {};
    try { map = JSON.parse(fs.readFileSync(out, "utf8")) || {}; } catch {}
    if (map[tile] === sid) return;
    map[tile] = sid;
    const tmp = out + ".tmp";
    fs.writeFileSync(tmp, JSON.stringify(map));
    fs.renameSync(tmp, out);
  } catch {}
});
`;
try { fs.writeFileSync(trackerPath, TRACKER_SRC); } catch { /* best-effort */ }

/** The merged SessionStart hook settings JSON for a given tile id. */
function trackerSettings(id: string): string {
  const hookCmd =
    `HIVEMIND_TILE='${id}' ELECTRON_RUN_AS_NODE=1 ` +
    `'${process.execPath}' '${trackerPath}' '${tileSessionsPath}'`;
  return JSON.stringify({
    hooks: { SessionStart: [{ hooks: [{ type: "command", command: hookCmd }] }] },
  });
}
/** Prepend our merged --settings (tracker hook) to a claude spec. Idempotent;
 *  skips if the spec already carries a --settings (user override). */
function withTracker(spec: SpawnSpec, id: string): SpawnSpec {
  const cmd = (spec.cmd ?? "").split("/").pop();
  if (cmd !== "claude") return spec;
  const args = spec.args ?? [];
  if (args.includes("--settings")) return spec;
  return { ...spec, args: ["--settings", trackerSettings(id), ...args] };
}
/** The live session id the tile is currently in, per the tracker map. */
function trackedSession(id: string): string | undefined {
  try {
    const map = JSON.parse(fs.readFileSync(tileSessionsPath, "utf8"));
    const v = map?.[id];
    return typeof v === "string" ? v : undefined;
  } catch { return undefined; }
}
const snapshotPath = (id: string): string => {
  // URL-safe base64 of the id so any character (including ':') is path-safe.
  const safe = Buffer.from(id).toString("base64url");
  return path.join(sessionsDir, `${safe}.json`);
};
function persistSnapshot(id: string, snap: SessionSnapshot): void {
  const p = snapshotPath(id);
  try {
    // Atomic-ish: write to a sibling tmp then rename (avoids torn JSON if the
    // process is killed mid-write — partial file would fail JSON.parse on
    // next boot and the session would be lost otherwise).
    const tmp = `${p}.tmp`;
    fs.writeFileSync(tmp, JSON.stringify(snap), "utf8");
    fs.renameSync(tmp, p);
  } catch {
    /* disk full / readonly fs — session loses reboot survival, that's it */
  }
}
function evictSnapshot(id: string): void {
  try { fs.unlinkSync(snapshotPath(id)); } catch { /* already gone */ }
  // Also drop the tile's tracked-session entry so tile-sessions.json doesn't
  // accumulate stale ids for killed tiles.
  try {
    const map = JSON.parse(fs.readFileSync(tileSessionsPath, "utf8"));
    if (map && id in map) {
      delete map[id];
      const tmp = `${tileSessionsPath}.tmp`;
      fs.writeFileSync(tmp, JSON.stringify(map));
      fs.renameSync(tmp, tileSessionsPath);
    }
  } catch { /* no map yet / unreadable — nothing to clean */ }
}
function loadAllSnapshots(): SessionSnapshot[] {
  const out: SessionSnapshot[] = [];
  let names: string[] = [];
  try { names = fs.readdirSync(sessionsDir); } catch { return out; }
  for (const name of names) {
    if (!name.endsWith(".json")) continue;
    const filePath = path.join(sessionsDir, name);
    try {
      const raw = fs.readFileSync(filePath, "utf8");
      const snap = JSON.parse(raw) as SessionSnapshot;
      // Basic shape sanity — old/corrupt snapshots are silently dropped.
      if (!snap || typeof snap.id !== "string" || typeof snap.replay !== "string" || !snap.spec) {
        continue;
      }
      // Legacy key shape (`hm:<absolute-path>:<tileId>` — 3+ colon-segments
      // after `hm:`). The new key is `hm:<tileId>` (single segment). No
      // renderer asks for the legacy id anymore — they'd be loaded into the
      // frozen map every daemon boot and never attached, leaking memory
      // forever. Drop both the in-memory load AND the on-disk file.
      if (snap.id.startsWith("hm:") && snap.id.slice(3).split(":").length > 1) {
        try { fs.unlinkSync(filePath); } catch { /* already gone */ }
        continue;
      }
      out.push(snap);
    } catch {
      /* corrupt — skip */
    }
  }
  return out;
}

// Real node-pty factory. Mirrors pty-host.doSpawn's env defaults so colors,
// locale, and TERM_PROGRAM match the in-process path. UUID injection happens
// in transformSpecOnSpawn (so the snapshot persists it) — by the time spec
// reaches here, the args already carry `--session-id <uuid>` for claude.
const factory = (spec: SpawnSpec): ManagedPty => {
  const env: Record<string, string> = {
    ...(process.env as Record<string, string>),
    ...(spec.env ?? {}),
  };
  if (!env.COLORTERM) env.COLORTERM = "truecolor";
  if (!env.LANG) env.LANG = "C.UTF-8";
  if (!env.TERM_PROGRAM) env.TERM_PROGRAM = "hivemind";
  const p = pty.spawn(spec.cmd, spec.args ?? [], {
    cwd: spec.cwd,
    cols: spec.cols,
    rows: spec.rows,
    name: "xterm-256color",
    env,
  });
  return {
    get pid() {
      return p.pid;
    },
    write: (d) => p.write(d),
    resize: (c, r) => p.resize(c, r),
    kill: (sig) => p.kill(sig),
    onData: (cb) => p.onData(cb),
    onExit: (cb) => p.onExit(({ exitCode, signal }) => cb(exitCode, signal)),
  };
};

const manager = new SessionManager(factory, {
  idleMs: 8000, // exit 8s after the last session is killed/exits — no orphans
  onEmpty: () => {
    try {
      server.close();
    } catch {
      /* ignore */
    }
    process.exit(0);
  },
  onSnapshot: persistSnapshot,
  onSnapshotEvict: evictSnapshot,
  // BIND-AT-SPAWN: every fresh claude session gets a hivemind-generated UUID
  // via `--session-id`. The UUID is stored in the snapshot's args, so restore
  // is deterministic — no `--continue` lottery (which silently starts fresh
  // on miss, anthropics/claude-code #10063), no `~/.claude/projects/` polling
  // to discover the id. Falls back to `--continue` if the snapshot pre-dates
  // this binding (i.e. legacy snapshots from before today's build).
  // Limitations still inherited from claude itself (cannot fix from PTY layer):
  //   - Killed MID-TOOL-CALL → JSONL ends with tool_use, --resume crashes (#18880).
  //   - Post-`cd` mid-session → persistence stops (#22566).
  //   - Version-upgrade across resume → silent persistence loss (#53417).
  transformSpecOnSpawn: (spec, id) => {
    const cmd = (spec.cmd ?? "").split("/").pop();
    if (cmd !== "claude") return spec;
    const args = spec.args ?? [];
    // User-provided session control wins (--session-id, --resume, --continue,
    // --from-pr) — those are explicit overrides.
    const claimed = args.some((a) =>
      a === "--session-id" || a === "--resume" || a === "-r" ||
      a === "--continue" || a === "-c" || a === "--from-pr",
    );
    const withId = claimed ? spec : { ...spec, args: ["--session-id", randomUUID(), ...args] };
    // Inject the SessionStart tracker so we follow /resume switches.
    return withTracker(withId, id);
  },
  transformSpecOnRestore: (spec, id) => {
    const cmd = (spec.cmd ?? "").split("/").pop();
    if (cmd !== "claude") return spec;
    const args = spec.args ?? [];
    // PREFER the live session the tile was last in (tracked via the SessionStart
    // hook) — this follows a `/resume <other>` the user did inside the tile, or
    // any id claude reassigned. Falls through to the snapshot's --session-id.
    const tracked = trackedSession(id);
    if (tracked) {
      const sidIdx0 = args.indexOf("--session-id");
      const base = sidIdx0 >= 0 ? [...args.slice(0, sidIdx0), ...args.slice(sidIdx0 + 2)] : args;
      return withTracker({ ...spec, args: ["--resume", tracked, ...base] }, id);
    }
    // Swap `--session-id <uuid>` → `--resume <uuid>` for deterministic
    // resume. claude does NOT auto-resume on a bare `--session-id <uuid>`
    // when the JSONL already exists (verified by user: resume was broken
    // when we kept --session-id). `--resume` is the only way to actually
    // continue an existing conversation.
    //
    // `--resume` LOUD-errors when JSONL is missing ("No conversation found
    // with session ID: …" → exit 1). That used to kill the tile dead. Now
    // SessionManager has a `restoreRetryTransform` that respawns once with
    // `--session-id <uuid>` (creates a new session bound to the same uuid)
    // when the first attempt exits non-zero within ~5s — preserves both
    // resume-on-happy-path AND no-crash-on-miss.
    const sidIdx = args.indexOf("--session-id");
    if (sidIdx >= 0 && sidIdx + 1 < args.length) {
      const uuid = args[sidIdx + 1]!;
      const next = [...args.slice(0, sidIdx), ...args.slice(sidIdx + 2)];
      return withTracker({ ...spec, args: ["--resume", uuid, ...next] }, id);
    }
    // Legacy snapshot (pre-bind era) — fall back to --continue best-effort.
    const claimed = args.some((a) =>
      a === "--resume" || a === "-r" || a === "--continue" || a === "-c",
    );
    if (claimed) return withTracker(spec, id);
    return withTracker({ ...spec, args: ["--continue", ...args] }, id);
  },
  // When a restored session exits with non-zero within this window, respawn
  // it once with this transform — turns "claude --resume <uuid> → No
  // conversation found → exit 1" into "claude --session-id <uuid>" (fresh
  // session, same deterministic id for future restores).
  restoreRetryMs: 5000,
  restoreRetryTransform: (spec) => {
    const cmd = (spec.cmd ?? "").split("/").pop();
    if (cmd !== "claude") return null;
    const args = spec.args ?? [];
    const rIdx = args.indexOf("--resume");
    if (rIdx < 0 || rIdx + 1 >= args.length) return null;
    const uuid = args[rIdx + 1]!;
    const next = [...args.slice(0, rIdx), ...args.slice(rIdx + 2)];
    return { ...spec, args: ["--session-id", uuid, ...next] };
  },
});

// Reboot-restore: hydrate any snapshots written by a previous daemon. They
// stay frozen (no live PTY) until a renderer attaches — only then is a fresh
// PTY spawned with the stored spec. Idle-exit is held off because frozen
// sessions count as "available" (size > 0 is not enough — frozen.size is
// tracked separately by the manager).
for (const snap of loadAllSnapshots()) manager.restoreSnapshot(snap);

// Graceful shutdown — flush any unwritten snapshots before exit so the last
// ~2s of activity (the debounce window) survives an orderly daemon termination.
// MUST await: flushAll resolves only after every xterm-drain callback fires
// + the corresponding persistSnapshot completes. A sync `process.exit(0)` here
// would kill the event loop before any callback ran → snapshots silently lost
// (the bug shipped in the prior diff). `process.on("exit")` is intentionally
// NOT registered — that listener is sync-only per Node docs and can't await.
const flushOnExit = async (): Promise<void> => {
  try { await manager.flushAll(); } catch { /* ignore */ }
};
process.on("SIGTERM", () => { void flushOnExit().then(() => process.exit(0)); });
process.on("SIGINT", () => { void flushOnExit().then(() => process.exit(0)); });

// Clean up a stale socket from a previous (crashed) daemon before binding.
try {
  fs.unlinkSync(socketPath);
} catch {
  /* not present — fine */
}

const server = net.createServer((sock) => {
  const send = (msg: ServerMsg) => {
    if (!sock.destroyed) sock.write(frame(msg));
  };
  // Sessions this connection attached — detached (NOT killed) when it drops,
  // so closing the window leaves the processes running.
  const attached = new Set<string>();

  const onLine = makeLineDecoder((line) => {
    let msg: ClientMsg;
    try {
      msg = JSON.parse(line) as ClientMsg;
    } catch {
      return;
    }
    switch (msg.t) {
      case "attach": {
        attached.add(msg.id);
        void manager
          .createOrAttach(msg.id, msg.spec, {
            onData: (data) => send({ t: "data", id: msg.id, data }),
            onExit: (code, signal) =>
              send({ t: "exit", id: msg.id, code, signal: signal ?? null }),
          })
          .then((r) => {
            send({ t: "attached", reqId: msg.reqId, id: msg.id, pid: r.pid, isNew: r.isNew, replay: r.replay });
          });
        break;
      }
      case "write":
        manager.write(msg.id, msg.data);
        break;
      case "resize":
        manager.resize(msg.id, msg.cols, msg.rows);
        break;
      case "detach":
        attached.delete(msg.id);
        manager.detach(msg.id);
        break;
      case "kill":
        attached.delete(msg.id);
        manager.kill(msg.id);
        break;
      case "list":
        send({ t: "sessions", reqId: msg.reqId, ids: manager.list() });
        break;
      case "ping":
        send({ t: "pong", reqId: msg.reqId });
        break;
    }
  });

  sock.on("data", onLine);
  sock.on("error", () => {
    /* client vanished mid-write — ignore */
  });
  sock.on("close", () => {
    // Window closed: detach (keep processes alive). Never kill on disconnect.
    for (const id of attached) manager.detach(id);
    attached.clear();
  });
});

server.on("error", (e) => {
  console.error("[pty-daemon] server error:", e);
  process.exit(1);
});

server.listen(socketPath, () => {
  // stdout is ignored by the parent, but useful when run manually for debugging.
  console.error(`[pty-daemon] listening on ${socketPath} (pid ${process.pid})`);
});

// If nothing ever connects (parent died right after spawn), don't linger.
// Frozen sessions (loaded from disk) DON'T keep the daemon alive on boot —
// without a live client they'd just rot in memory. They stay safe on disk;
// the next daemon boot reloads them. `manager.list().length` covers both
// live AND frozen for fairness with other call sites.
const bootGuard = setTimeout(() => {
  if (manager.size() === 0) {
    // Flush any snapshots that were dirty (shouldn't be any — frozen aren't
    // dirty — but cheap insurance), then exit. Async-await so the snapshot
    // write completes before the process dies.
    void manager.flushAll().finally(() => process.exit(0));
  }
}, 30000);
bootGuard.unref?.();
